# GitHub Actions workflow for database unification regression testing
name: Database Unification Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  unification-checks:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install psycopg2-binary
        
    - name: Set up test database
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
      run: |
        # Create test schema and data
        psql $DATABASE_URL -c "CREATE TABLE IF NOT EXISTS expenses (id SERIAL PRIMARY KEY, idempotency_key VARCHAR(255));"
        psql $DATABASE_URL -c "CREATE TABLE IF NOT EXISTS inference_snapshots (id SERIAL PRIMARY KEY, intent VARCHAR(50), cc_id VARCHAR(255));"
        psql $DATABASE_URL -c "INSERT INTO expenses (idempotency_key) VALUES ('test');"
        
    - name: Run Database Unification Checks
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
      run: python3 ci_unification_checks.py
      
    - name: Run Bash Regression Tests (Alternative)
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
      run: ./test_unification_regression.sh